### ISSUE TITLE
EmulateIE9?

### ISSUE THREAD

**Issue by krijnhoetmer** [rovervannispen/Everything-Web-Minor#12]
Waarom wil je specifiek het IE9 gedrag hier hebben?

**Comment by rovervannispen** [comment]
Omdat ik aan het testen was op mijn VirtualBox en ik dit nog niet had weggehaald.

**Comment by rovervannispen** [comment]
Is nu weggehaald met de nieuwe commit

**Comment by KoopReynders** [comment]
done
